# Generated by Django 5.1.5 on 2025-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mentor',
            new_name='mentor_id',
        ),
    ]
