# Generated by Django 5.1.5 on 2025-04-02 16:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(help_text='Enter your date of birth in the format YYYY-MM-DD', validators=[core.validators.validate_dob]),
        ),
    ]
