# Generated by Django 5.1.5 on 2025-04-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_semester_to_subject'),
        ('core', 'add_semester_to_subject'),
    ]

    operations = [
    ]
