# Generated by Django 5.1.5 on 2025-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_csvinput_alter_student_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvinput',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'CSV Upload', 'verbose_name_plural': 'CSV Uploads'},
        ),
        migrations.AddField(
            model_name='csvinput',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
