# Generated by Django 5.1.5 on 2025-04-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_csvinput_options_csvinput_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvinput',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='csvinput',
            name='file',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
