# Generated by Django 5.1.5 on 2025-04-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_csvinput_original_filename_alter_csvinput_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvinput',
            name='original_filename',
        ),
        migrations.AlterField(
            model_name='csvinput',
            name='file',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
