# Generated by Django 5.1.5 on 2025-04-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_csvinput_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvinput',
            name='file',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
